// AUTO GENERATED BY JNIGEN 1.0.0. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

const _$jniVersionCheck = jni$_.JniVersionCheck(1, 0);

/// from: `com.alexmercerind.media_kit_video.VideoOutput`
extension type VideoOutput._(jni$_.JObject _$this)
    implements jni$_.JObject, TextureRegistry$$SurfaceProducer$$Callback {
  static final _class = jni$_.JClass.forName(
    r'com/alexmercerind/media_kit_video/VideoOutput',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<VideoOutput> type = $VideoOutput$Type$();
  static final _id_new$ = _class.constructorId(
    r'(Lcom/alexmercerind/media_kit_video/TextureUpdateCallback;)V',
  );

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(com.alexmercerind.media_kit_video.TextureUpdateCallback callback)`
  /// The returned object must be released after use, by calling the [release] method.
  factory VideoOutput(TextureUpdateCallback callback) {
    final _$$classRef = _class.reference;
    final _$callback = callback.reference;
    return _new$(
      _$$classRef.pointer,
      _id_new$.pointer,
      _$callback.pointer,
    ).object<VideoOutput>();
  }
}

extension VideoOutput$$Methods on VideoOutput {
  static final _id_dispose = VideoOutput._class.instanceMethodId(
    r'dispose',
    r'()V',
  );

  static final _dispose =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void dispose()`
  void dispose() {
    final _$$selfRef = reference;
    _dispose(_$$selfRef.pointer, _id_dispose.pointer).check();
  }

  static final _id_setSurfaceSize = VideoOutput._class.instanceMethodId(
    r'setSurfaceSize',
    r'(II)V',
  );

  static final _setSurfaceSize =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Int32, jni$_.Int32)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              core$_.int,
            )
          >();

  /// from: `public void setSurfaceSize(int width, int height)`
  void setSurfaceSize(core$_.int width, core$_.int height) {
    final _$$selfRef = reference;
    _setSurfaceSize(
      _$$selfRef.pointer,
      _id_setSurfaceSize.pointer,
      width,
      height,
    ).check();
  }

  static final _id_onSurfaceAvailable = VideoOutput._class.instanceMethodId(
    r'onSurfaceAvailable',
    r'()V',
  );

  static final _onSurfaceAvailable =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void onSurfaceAvailable()`
  void onSurfaceAvailable() {
    final _$$selfRef = reference;
    _onSurfaceAvailable(
      _$$selfRef.pointer,
      _id_onSurfaceAvailable.pointer,
    ).check();
  }

  static final _id_onSurfaceCleanup = VideoOutput._class.instanceMethodId(
    r'onSurfaceCleanup',
    r'()V',
  );

  static final _onSurfaceCleanup =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public void onSurfaceCleanup()`
  void onSurfaceCleanup() {
    final _$$selfRef = reference;
    _onSurfaceCleanup(_$$selfRef.pointer, _id_onSurfaceCleanup.pointer).check();
  }
}

final class $VideoOutput$Type$ extends jni$_.JType<VideoOutput> {
  @jni$_.internal
  const $VideoOutput$Type$();

  @jni$_.internal
  @core$_.override
  String get signature => r'Lcom/alexmercerind/media_kit_video/VideoOutput;';
}

/// from: `com.alexmercerind.media_kit_video.TextureUpdateCallback`
extension type TextureUpdateCallback._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'com/alexmercerind/media_kit_video/TextureUpdateCallback',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<TextureUpdateCallback> type =
      $TextureUpdateCallback$Type$();

  /// Maps a specific port to the implemented interface.
  static final core$_.Map<core$_.int, $TextureUpdateCallback> _$impls = {};
  static jni$_.JObjectPtr _$invoke(
    core$_.int port,
    jni$_.JObjectPtr descriptor,
    jni$_.JObjectPtr args,
  ) {
    return _$invokeMethod(
      port,
      jni$_.MethodInvocation.fromAddresses(0, descriptor.address, args.address),
    );
  }

  static final jni$_.Pointer<
    jni$_.NativeFunction<
      jni$_.JObjectPtr Function(jni$_.Int64, jni$_.JObjectPtr, jni$_.JObjectPtr)
    >
  >
  _$invokePointer = jni$_.Pointer.fromFunction(_$invoke);

  static jni$_.Pointer<jni$_.Void> _$invokeMethod(
    core$_.int $p,
    jni$_.MethodInvocation $i,
  ) {
    try {
      final $d = $i.methodDescriptor.toDartString(releaseOriginal: true);
      final $a = $i.args;
      if ($d == r'onTextureUpdate(JLjava/lang/Object;II)V') {
        _$impls[$p]!.onTextureUpdate(
          ($a![0] as jni$_.JLong).toDartInt(releaseOriginal: true),
          ($a![1] as jni$_.JObject?),
          ($a![2] as jni$_.JInteger).toDartInt(releaseOriginal: true),
          ($a![3] as jni$_.JInteger).toDartInt(releaseOriginal: true),
        );
        return jni$_.nullptr;
      }
    } catch (e) {
      return jni$_.ProtectedJniExtensions.newDartException(e);
    }
    return jni$_.nullptr;
  }

  static void implementIn(
    jni$_.JImplementer implementer,
    $TextureUpdateCallback $impl,
  ) {
    late final jni$_.RawReceivePort $p;
    $p = jni$_.RawReceivePort(($m) {
      if ($m == null) {
        _$impls.remove($p.sendPort.nativePort);
        $p.close();
        return;
      }
      final $i = jni$_.MethodInvocation.fromMessage($m);
      final $r = _$invokeMethod($p.sendPort.nativePort, $i);
      $i.args?.release();
      jni$_.ProtectedJniExtensions.returnResult($i.result, $r);
    });
    implementer.add(
      r'com.alexmercerind.media_kit_video.TextureUpdateCallback',
      $p,
      _$invokePointer,
      [
        if ($impl.onTextureUpdate$async)
          r'onTextureUpdate(JLjava/lang/Object;II)V',
      ],
    );
    final $a = $p.sendPort.nativePort;
    _$impls[$a] = $impl;
  }

  factory TextureUpdateCallback.implement($TextureUpdateCallback $impl) {
    final $i = jni$_.JImplementer();
    implementIn($i, $impl);
    return $i.implement<TextureUpdateCallback>();
  }
}

extension TextureUpdateCallback$$Methods on TextureUpdateCallback {
  static final _id_onTextureUpdate = TextureUpdateCallback._class
      .instanceMethodId(r'onTextureUpdate', r'(JLjava/lang/Object;II)V');

  static final _onTextureUpdate =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<
                  (
                    jni$_.Int64,
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.Int32,
                    jni$_.Int32,
                  )
                >,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.int,
              jni$_.Pointer<jni$_.Void>,
              core$_.int,
              core$_.int,
            )
          >();

  /// from: `public abstract void onTextureUpdate(long id, java.lang.Object surface, int width, int height)`
  ///
  /// @param id Flutter texture id
  ///@param surface android.view.Surface (null if cleaned up)
  ///@param width surface width
  ///@param height surface height
  void onTextureUpdate(
    core$_.int id,
    jni$_.JObject? surface,
    core$_.int width,
    core$_.int height,
  ) {
    final _$$selfRef = reference;
    final _$surface = surface?.reference ?? jni$_.jNullReference;
    _onTextureUpdate(
      _$$selfRef.pointer,
      _id_onTextureUpdate.pointer,
      id,
      _$surface.pointer,
      width,
      height,
    ).check();
  }
}

abstract base mixin class $TextureUpdateCallback {
  factory $TextureUpdateCallback({
    required void Function(
      core$_.int id,
      jni$_.JObject? surface,
      core$_.int width,
      core$_.int height,
    )
    onTextureUpdate,
    core$_.bool onTextureUpdate$async,
  }) = _$TextureUpdateCallback;

  void onTextureUpdate(
    core$_.int id,
    jni$_.JObject? surface,
    core$_.int width,
    core$_.int height,
  );
  core$_.bool get onTextureUpdate$async => false;
}

final class _$TextureUpdateCallback with $TextureUpdateCallback {
  _$TextureUpdateCallback({
    required void Function(
      core$_.int id,
      jni$_.JObject? surface,
      core$_.int width,
      core$_.int height,
    )
    onTextureUpdate,
    this.onTextureUpdate$async = false,
  }) : _onTextureUpdate = onTextureUpdate;

  final void Function(
    core$_.int id,
    jni$_.JObject? surface,
    core$_.int width,
    core$_.int height,
  )
  _onTextureUpdate;
  final core$_.bool onTextureUpdate$async;

  void onTextureUpdate(
    core$_.int id,
    jni$_.JObject? surface,
    core$_.int width,
    core$_.int height,
  ) {
    return _onTextureUpdate(id, surface, width, height);
  }
}

final class $TextureUpdateCallback$Type$
    extends jni$_.JType<TextureUpdateCallback> {
  @jni$_.internal
  const $TextureUpdateCallback$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lcom/alexmercerind/media_kit_video/TextureUpdateCallback;';
}

/// from: `io.flutter.view.TextureRegistry$SurfaceProducer$Callback`
///
/// WARNING: TextureRegistry$$SurfaceProducer$$Callback is a stub. To generate bindings for this class, include
/// io.flutter.view.TextureRegistry$SurfaceProducer$Callback in your config's classes list.
///
extension type TextureRegistry$$SurfaceProducer$$Callback._(
  jni$_.JObject _$this
)
    implements jni$_.JObject {
  static const jni$_.JType<TextureRegistry$$SurfaceProducer$$Callback> type =
      $TextureRegistry$$SurfaceProducer$$Callback$Type$();
}

final class $TextureRegistry$$SurfaceProducer$$Callback$Type$
    extends jni$_.JType<TextureRegistry$$SurfaceProducer$$Callback> {
  @jni$_.internal
  const $TextureRegistry$$SurfaceProducer$$Callback$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lio/flutter/view/TextureRegistry$SurfaceProducer$Callback;';
}
