name: media_kit
description: A cross-platform video player & audio player for Flutter & Dart. Performant, stable, feature-proof & modular.
homepage: https://github.com/media-kit/media-kit
repository: https://github.com/media-kit/media-kit
version: 1.2.6
environment:
  sdk: ">=3.8.0 <4.0.0"
resolution: workspace

screenshots:
  - description: "package:media_kit running on Android (visible controls)"
    path: screenshots/android_0.jpg
  - description: "package:media_kit running on Android"
    path: screenshots/android_1.jpg
  - description: "package:media_kit running on iOS (visible controls)"
    path: screenshots/ios_0.jpg
  - description: "package:media_kit running on iOS"
    path: screenshots/ios_1.jpg
  - description: "package:media_kit running on macOS"
    path: screenshots/macos.jpg
  - description: "package:media_kit running on Microsoft Windows"
    path: screenshots/windows.jpg
  - description: "package:media_kit running on GNU/Linux"
    path: screenshots/linux.jpg
  - description: "package:media_kit running on web"
    path: screenshots/web.jpg

topics:
  - video
  - video-player
  - audio
  - audio-player
  - cross-platform

dependencies:
  collection: ^1.19.0
  jni: ^1.0.3
  meta: ^1.15.0
  path: ^1.9.1
  synchronized: ^3.3.0

dev_dependencies:
  lints: any
  test: any
  http: any

ffigen:
  name: MPV
  output: lib/generated/libmpv/bindings.dart
  headers:
    entry-points:
      - headers/client.h
  type-map:
    native-types:
      char:
        lib: ffi
        c-type: Uint8
        dart-type: int
  exclude-all-by-default: true
  enums:
    include:
      - 'mpv_.*'
    as-int:
      exclude: []
  functions:
    include:
      - 'mpv_.*'
    leaf:
      include:
        - 'mpv_get_time_ns'
        - 'mpv_get_time_us'
        - 'mpv_client_name'
        - 'mpv_client_id'
        - 'mpv_client_api_version'
        - 'mpv_event_name'
        - 'mpv_error_string'
  structs:
    include:
      - 'mpv_.*'
  unions:
    include:
      - 'mpv_.*'
  globals:
    include:
      - 'mpv_.*'
  macros:
    include:
      - 'mpv_.*'
