import java.io.File
import java.nio.file.Files
import java.security.MessageDigest

group 'com.alexmercerind.media_kit_libs_android_video'
version '1.0'

buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.13.0'
    }
}

rootProject.allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

apply plugin: 'com.android.library'

android {
    // Conditional for compatibility with AGP <4.2.
    if (project.android.hasProperty("namespace")) {
        namespace 'com.alexmercerind.media_kit_libs_android_video'
    }

    compileSdkVersion 36

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        minSdkVersion 16
    }

    dependencies {
        implementation fileTree(dir: "$buildDir/output", include: "*.jar")
    }
}

task downloadDependencies(type: Exec) {
        // Delete previously created /output subdirectory.

        def outputDir = file("$buildDir/output")
        if (outputDir.exists()) {
            outputDir.deleteDir()
        }
        outputDir.mkdirs()

        // Download all *.jar dependencies & verify their sha256 checksums.
        def filesToDownload = [
            ["url": "https://github.com/My-Responsitories/libmpv-android-video-build/releases/download/20260930/default-arm64-v8a.jar", "sha256": "f6e11847ae1b7f3c55706881067d34cd119b3ab96f320688dbafc896f14968b1", "destination": file("$buildDir/20260930/default-arm64-v8a.jar")],
            ["url": "https://github.com/My-Responsitories/libmpv-android-video-build/releases/download/20260930/default-armeabi-v7a.jar", "sha256": "5a4d42552aaf32967ec1e5dbfdd3ca335ef42bb6dcc631ca99f6827f528f22ab", "destination": file("$buildDir/20260930/default-armeabi-v7a.jar")],
            ["url": "https://github.com/My-Responsitories/libmpv-android-video-build/releases/download/20260930/default-x86_64.jar", "sha256": "83a178be7505152d0627137c9f03a632d217b3eb63b0eef07e4f1b49931cfa83", "destination": file("$buildDir/20260930/default-x86_64.jar")],
        ]

        filesToDownload.each { fileInfo ->
            def destFile = fileInfo.destination
            if (destFile.exists()) {
                def calculatedSHA256 = MessageDigest.getInstance("SHA-256").digest(Files.readAllBytes(destFile.toPath())).encodeHex().toString()

                if (calculatedSHA256 != fileInfo.sha256) {
                    destFile.delete()
                    println "SHA-256 mismatch. File deleted: ${destFile}"
                }

            }

            if (!destFile.exists()) {
                destFile.parentFile.mkdirs()
                println "Downloading file from: ${fileInfo.url}"
                destFile.withOutputStream { os ->
                    os << new URL(fileInfo.url).openStream()
                }

                def calculatedSHA256 = MessageDigest.getInstance("SHA-256").digest(Files.readAllBytes(destFile.toPath())).encodeHex().toString()
                if (calculatedSHA256 != fileInfo.sha256) {
                    throw new GradleException("SHA-256 verification failed for ${destFile}")
                }
            }

            copy {
                from destFile
                into outputDir
            }
        }
}

assemble.dependsOn(downloadDependencies)